USE CORRESPONDENCIA
GO
CREATE VIEW VistaRespuesta AS
	Select CR.NOMBRE+' '+CR.APELLIDO_PATERNO AS "NombreRemitente",CR.CORREO AS "CorreoRemitente", CR.TELEFONO AS "TelefonoRemitente",
			CR.CARGO AS "Cargo",CO.NOMBRE AS "DireccionOrigen",CT.TIPO As "TipoDocumento", D.RESUMEN AS "Resumen", D.RESPUESTA AS "Respuesta"
			FROM ((((TBL_DOCUMENTOS AS D
				JOIN CAT_REMITENTES AS  CR
					ON CR.ID_REMITENTE=D.ID_REMITENTE)
				JOIN CAT_ORIGENES AS CO
					ON CO.ID_ORIGEN = CR.ID_ORIGEN)
				JOIN CAT_TIPO AS CT
					ON CT.ID_TIPO=D.ID_TIPO_DOC)
					);
